---
title: "11_atpRanking_byAge"
author: "Duc-Quang Nguyen"
date: "28 June 2016"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyr)
library(ggplot2)
library(swiTheme)

atpRanking.file <- "input/alln1_ATP_ranking.csv"
n1_dob.file <- "input/alln1_dob.csv"

```

```{r shape data}
# load data
n1rank <- read.csv(atpRanking.file, check.names = F, row.names = 1)

dob <- read.csv(n1_dob.file, stringsAsFactors = F)
dob <- structure(as.Date(dob[,2], format = "%Y.%m.%d"), names = dob[,1])

dates <- as.Date(row.names(n1rank), format = "%m/%d/%Y")
n1rank <- cbind(dates = dates, n1rank)
# make data long
n1rank %<>% gather(player, rank, -dates)
# add dob
n1rank$dob <- dob[match(n1rank$player, names(dob))]

# compute age
n1rank$age <- as.numeric(round((n1rank$dates - n1rank$dob) / 365.25, 1))

p <- ggplot(data = n1rank, aes(age, rank)) + geom_line(aes(group = player, colour = player)) + geom_smooth() + swi_theme()

player.sub <- c("Roger Federer", "Pete Sampras", "Ivan Lendl", "Novak Djokovic", "Rafael Nadal", "John McEnroe", "Jimmy Connors")
ggplot(data = filter(n1rank, player %in% player.sub), aes(age, rank)) + geom_line(aes(group = player, colour = player)) + xlim(c(16, 45)) + swi_theme()

# lo <- loess(rank ~ age | player, n1rank)
# predict(lo, data.frame(age = seq(1:50)), se = TRUE)


```