---
title: "02_heatmap_n1_ATP"
author: "Duc-Quang Nguyen"
date: "26 June 2016"
output: html_document
---

```{r setup, include=FALSE}
library(zoo)
library(dplyr)
library(magrittr)
library(tidyr)
library(ggplot2)
library(scales)
library(swiTheme)
library(viridisLite)
library(htmltools)
library(ggiraph)
library(swiRcharts)

atpRanking.file <- "input/alln1_ATP_ranking.csv"
n1_nationality.file <- "input/alln1_nationlity.csv"

```

```{r shape data}
# load data
n1rank <- read.csv(atpRanking.file, check.names = F, row.names = 1)

nat <- read.csv(n1_nationality.file, stringsAsFactors = F)
nat <- structure(nat[,2], names = nat[,1])
# convert to zoo
zn1 <- zoo(as.matrix(n1rank), as.Date(row.names(n1rank), format = "%m/%d/%Y"))
dates <- index(zn1)
date.reg <- c(seq(min(dates), max(dates), 7))
date.reg <- date.reg[order(date.reg)]

idx <- findInterval(date.reg, index(zn1), rightmost.closed = FALSE, all.inside = FALSE)
eq.zn1 <- zoo(unclass(zn1)[idx,], date.reg)

stopifnot(!any(duplicated(index(eq.zn1))) )
ranks <- max(eq.zn1, na.rm =T)

# ugly hack to fill ranking before 1985
dateLabel <- rep("", length(date.reg))
ii <- which(!duplicated(format(date.reg, format = "%Y")))
dateLabel[ii[-1]] <- format(date.reg[ii[-1]], "%Y")
dateLabel[ii[1]] <- format(date.reg[ii[1]], "%Y-%m-%d")

# tranform back zoo to data.frame for ggplot2
n1 <- as.data.frame(eq.zn1)
n1 <- cbind(dates = as.Date(as.character(rownames(n1))), n1)
rownames(n1) <- NULL

n1 %<>% gather(player, rank, -dates)
n1$lrank <- log10(n1$rank)

# order data.frame by chronological order of players when the reached n1
n1.dates <- n1 %>% 
  group_by(player) %>% summarise(first1 = dates[min(which(rank == 1))]) %>% 
  ungroup() %>% arrange(first1)
#  make ordered factor player
n1$player <- factor(n1$player, levels = n1.dates$player)

# check dates spacing
stopifnot(all(diff(unique(n1$dates))==7))

narow <- n1 %>% group_by(dates) %>% 
  summarise(narow = all(is.na(rank))) %>% ungroup()
naidx <- which(narow %>% select(narow) %>% unlist())
if(length(naidx)>0) {
  warning(narow[naidx,], " hack will ensue")
  naDates <- as.Date(unlist(narow[naidx,'dates']), use.names = F)
  
  n1$dates.end <- n1$dates + 7
  # for NA dates, discard data and add a week to dates.end
  n1 %<>% filter(!dates %in% naDates)
  n1[which(n1$dates %in% (naDates-7)), 'dates.end'] <- n1[which(n1$dates %in% (naDates-7)), 'dates.end'] + 7
  
}


```

## Plot

* Check this use of [geom_rect](https://nsaunders.wordpress.com/2015/04/15/project-tycho-ggplot2-and-the-shameless-stealing-of-blog-ideas/)

```{r heatmap variant without faceting}
## Helpers and settings
htheme <- function() {
  swi_theme(y_gridlines = F) + 
    theme(
      axis.ticks.length=unit(3, "pt"),
      axis.ticks.y = element_blank(),
      axis.text.y = element_blank(),
      axis.line = element_blank(),
      axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
      axis.title = element_blank(),
      legend.position=c(0.1, 0.95),
      legend.key.height = unit(0.7, "lines"),
      legend.key.width = unit(0.8, "lines"),
      legend.direction = "horizontal",
      legend.title = element_text(vjust = 0)
    )
}

rect.h <- 9
rect.spacing <- 1
rect.y <- rect.h + rect.spacing
plab.offset <- 7 * 11

# define ymin & ymax for geom_rect
n1r <- do.call(rbind, lapply(1:nlevels(n1$player), function(i) {
  cbind(
    n1 %>% filter(player == levels(n1$player)[i]), 
    ymin = rect.y * (i-1),
    ymax = (rect.y * (i-1)) + rect.h
  )
}))
n1r %<>% group_by(player) %>% mutate(y = (ymin + ymax) / 2) %>% ungroup()

# define the rect labels, player name
player.lab <- n1r %>% group_by(player, y) %>% 
  summarise(x = dates[max(which(!is.na(rank)))] + plab.offset) %>% ungroup()
# hack to manually aligned some player names vertically
player.lab.aligned <- player.lab
player.lab.aligned[1:2, 'x'] <- player.lab[1, 'x']
player.lab.aligned[3:8, 'x'] <- player.lab[player.lab$player == "Stefan Edberg", 'x']
player.lab.aligned[9:10, 'x'] <- player.lab[player.lab$player == "Jim Courier", 'x']
player.lab.aligned[13:19, 'x'] <- player.lab[13, 'x']
player.lab.aligned[20:25, 'x'] <- player.lab[25, 'x']
# add country names to player names
player.lab.aligned$player <- paste0(player.lab.aligned$player, " (", nat[match(player.lab.aligned$player, names(nat))], ")")

years <- unique(format(unique(n1r$dates), "%Y"))

## PLOT ##
hatp <- ggplot(n1r) + 
  geom_rect(
    aes(xmin = dates, xmax = dates.end, ymin = ymin, ymax = ymax, fill = lrank)) + 
  htheme() +
  # to overwrite colour label scale legend
  scale_fill_gradientn(
    name = "ATP ranking",
    colours = viridis(1000, option = "D"),
    na.value = "transparent",
    labels=as.character(c(10^0, 10^1, 10^2, 10^3))
  ) + 
  scale_x_date(
    name = "",
    breaks = c(min(n1r$dates), as.Date(paste0(years[-c(1,2, length(years))], "-01-01")), max(n1r$dates)),
    labels =  c(as.character(min(n1r$dates)), years[-c(1,2, length(years))], as.character(max(n1r$dates))),
    expand = c(0, 0), 
    limits = c(min(n1r$dates), max(n1r$dates) + 1300)
  ) +
  scale_y_continuous(expand = c(0.01, 0)) + 
  geom_text(
    data = player.lab.aligned,
    aes(x = x, y = y, label = player), hjust = 0,
      family = "OpenSans-CondensedLight",
    size=2.9, color="#2b2b2b")

#hatp

  save_html(
    tags$html(
     tags$head(includeHTML("styles.html")),
      tags$body(    
      div(class="container",
        div(class="graphic", 
            ggiraph(code = {print(hatp)},  fontname_sans = 'Open Sans Condensed',   width = "100%"))
      ),
      HTML(iframeresizer)  
    )), file = paste0("test_svg_heatmap.html")
  )
  
  

```
